Cb emp
SlothfulSheep/bangazon-api-sprint1 pull request #20
Opened 2018-03-23 17:22 UTC by CourtneyBrothers

# Description

Expose employee resource
verbs to be supported 
GET
POST
PUT

Fixes #6 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X ] This change requires a documentation update

# How Has This Been Tested?
1) run nodemon app.js in the project directory

2) to getAllEmployees visit http://localhost:<_your_port number>/api/v1/employees
this should serve the customers JSON 

3) to getOneEmployee  visit http://localhost:<_your_port number>/api/v1/employees/_employee_id

4)postOneEmployee

recommended to use postman to pass employee object 
example: 
{
first_name: "Afton",
last_name: "Kessler",
dept_id: 10
}

POST: localhost:<_your_port number>/api/v1/employees

employee will be added at next primary integer position to the list of employees

PUT:localhost:<_your_port number>/api/v1/employees/_employee_id

employee object will replace the employee object at the _employee_id position specified in the http request 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [X ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2018-03-25 17:36 UTC, iiimosley requested changes
- Found a few spots in `Employee` model where quotes were inserted around integer values. Please remove so proper integer format may be inserted into the rows.  (see line comments)
- Please reformat your example JSON data in PR to match parameters passed into your `PUT` and `POST` model functions:
  - camelCase rather than snake_case
  - quotes around all keys and string values

Everything else looks great!

2018-03-25 17:36 UTC, iiimosley commented on models/Employee.js
> +    db.run(`UPDATE employees SET employee_id = ${id},first_name = "${firstName}",last_name ="${lastName}",dept_id="${deptId}" WHERE employee_id =${id}`, (err, emp) => {
please remove quotes from `deptId` string interpolation to render value as an integer

2018-03-25 17:36 UTC, iiimosley commented on models/Employee.js
> +    db.run(`INSERT INTO employees VALUES(${null},"${firstName}","${lastName}","${deptId}")`, (err, emp) => {
please remove quotes from `deptId` string interpolation to render value as an integer

2018-03-25 17:36 UTC, iiimosley commented on models/Employee.js
> +    db.all(`SELECT * FROM employees WHERE employee_id = "${id}"`, (err, emp) => {
please remove quotes from `id` string interpolation to render value as an integer

2018-03-26 14:26 UTC, CourtneyBrothers commented
@iiimosley hey i did this

2018-03-26 14:53 UTC, iiimosley approved these changes

2018-03-26 14:55 UTC, iiimosley reviewed
Totes sauce, it has been did.  Thank you!  🍠

2018-03-26 14:56 UTC, EliOJackson approved these changes
I was able to complete all queries 🥇 🎉

2018-03-26 14:59 UTC, merged